In [1]:
import pandas as pd

In [2]:
df_15min = pd.read_csv('../data/afeka/germany_thin.csv', parse_dates=['utc_timestamp'])
df_15min

,utc_timestamp,load_actual_entsoe_transparency,load_forecast_entsoe_transparency
0,2015-01-01 00:15:00+00:00,41517.72,40204.18
1,2015-01-01 00:30:00+00:00,41179.17,39640.26
2,2015-01-01 00:45:00+00:00,40756.40,39323.88
3,2015-01-01 01:00:00+00:00,40617.76,39002.42
4,2015-01-01 01:15:00+00:00,40312.25,38869.21
...,...,...,...
201295,2020-09-30 22:30:00+00:00,46505.50,46360.69
201296,2020-09-30 22:45:00+00:00,46229.48,45971.68
201297,2020-09-30 23:00:00+00:00,45792.82,45303.45
201298,2020-09-30 23:15:00+00:00,45471.18,44987.77
201299,2020-09-30 23:30:00+00:00,45119.89,44668.15

In [4]:
data = df_15min.copy()

# Add percentage error
data['perr'] = (data['load_actual_entsoe_transparency'] - data['load_forecast_entsoe_transparency']) / data['load_actual_entsoe_transparency']
data

,utc_timestamp,load_actual_entsoe_transparency,load_forecast_entsoe_transparency,perr
0,2015-01-01 00:15:00+00:00,41517.72,40204.18,0.031638
1,2015-01-01 00:30:00+00:00,41179.17,39640.26,0.037371
2,2015-01-01 00:45:00+00:00,40756.40,39323.88,0.035148
3,2015-01-01 01:00:00+00:00,40617.76,39002.42,0.039769
4,2015-01-01 01:15:00+00:00,40312.25,38869.21,0.035797
...,...,...,...,...
201295,2020-09-30 22:30:00+00:00,46505.50,46360.69,0.003114
201296,2020-09-30 22:45:00+00:00,46229.48,45971.68,0.005577
201297,2020-09-30 23:00:00+00:00,45792.82,45303.45,0.010687
201298,2020-09-30 23:15:00+00:00,45471.18,44987.77,0.010631
201299,2020-09-30 23:30:00+00:00,45119.89,44668.15,0.010012

# Predictions from ENTSOE have MAPE of 3%, while best predictions obtained by models from this project are around 2.5%!!!

In [5]:
# Compute Mean Absolute Percentage Error (MAPE)
mape = data['perr'].abs().mean()

print("Mean Absolute Percentage Error (MAPE):", mape)

Mean Absolute Percentage Error (MAPE): 0.03076338541535403